/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package werdna;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import static werdna.UI.getProductButton;
import werdna.items.Whisky;
import werdna.items.Whisky_Data;

/**
 *
 * @author Andre
 */
public class epos extends javax.swing.JFrame {

    /**
     * Creates new form epos
     */
    JButton buttonTemplate;
    
    
    public epos() {
        initComponents();
        setTabs();
    }
    
    private void setTabs()
    {
        setButton();
        setSelected();
    }
    
    private void setSelected()
    {
        txtCountSelected.setBounds(64, 27, txtCountSelected.getX(), txtCountSelected.getY());
        txtCountSelected.setHorizontalAlignment(JTextField.CENTER);
        tabs.setEnabledAt(1, false);
    }
    
    private void setButton()
    {
        //<editor-fold defaultstate="collapsed" desc="Example of buttons working">
        /*String[] exampleList = {
            "whisky1", 
            "whisky2", 
            "whisky3", 
            "whisky4", 
            "whisky5", 
            "whisky6", 
            "whisky7", 
            "whisky8", 
            "whisky9", 
            "whisky10",
            "whisky11", 
            "whisky12", 
            "whisky13", 
            "whisky14", 
            "whisky15", 
            "whisky16", 
            "whisky17", 
            "whisky18", 
            "whisky19", 
            "whisky20",
            "whisky1", 
            "whisky2", 
            "whisky3", 
            "whisky4", 
            "whisky5", 
            "whisky6", 
            "whisky7", 
            "whisky8", 
            "whisky9", 
            "whisky10",
            "whisky11", 
            "whisky12", 
            "whisky13", 
            "whisky14", 
            "whisky15", 
            "whisky16", 
            "whisky17", 
            "whisky18", 
            "whisky19", 
            "whisky20"
        };*/
        
        //Example ArrayList<JButton> btns = UI.getProductButtons(exampleList);
        //</editor-fold>
        
        ArrayList<JButton> btns = getProductButtons(Whisky_Data.getWhiskys());
        pnlProducts.setPreferredSize(new Dimension(380,(btns.size()/3)*130));
        for(JButton btn : btns)
        {
            pnlProducts.add(btn);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tabs = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlProducts = new javax.swing.JPanel();
        pnlSelectedItem = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAddBasket = new javax.swing.JButton();
        txtCountSelected = new javax.swing.JTextField();
        btnIncSelected = new javax.swing.JButton();
        btnDecSelected = new javax.swing.JButton();
        lblSelectedProductName = new javax.swing.JLabel();
        pnlBasket = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnlBasetItems = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdmin = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlProducts.setPreferredSize(new java.awt.Dimension(380, 1000));

        javax.swing.GroupLayout pnlProductsLayout = new javax.swing.GroupLayout(pnlProducts);
        pnlProducts.setLayout(pnlProductsLayout);
        pnlProductsLayout.setHorizontalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );
        pnlProductsLayout.setVerticalGroup(
            pnlProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlProducts);

        tabs.addTab("Products", jScrollPane1);

        txtDescription.setEditable(false);
        txtDescription.setColumns(20);
        txtDescription.setLineWrap(true);
        txtDescription.setRows(5);
        jScrollPane3.setViewportView(txtDescription);

        btnAddBasket.setText("Add to Basket");

        txtCountSelected.setText("1");
        txtCountSelected.setAutoscrolls(false);
        txtCountSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountSelectedActionPerformed(evt);
            }
        });

        btnIncSelected.setText(">");
        btnIncSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncSelectedActionPerformed(evt);
            }
        });

        btnDecSelected.setText("<");
        btnDecSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecSelectedActionPerformed(evt);
            }
        });

        lblSelectedProductName.setText("productName");

        javax.swing.GroupLayout pnlSelectedItemLayout = new javax.swing.GroupLayout(pnlSelectedItem);
        pnlSelectedItem.setLayout(pnlSelectedItemLayout);
        pnlSelectedItemLayout.setHorizontalGroup(
            pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectedItemLayout.createSequentialGroup()
                .addGroup(pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSelectedItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddBasket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectedItemLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDecSelected)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIncSelected)
                                .addGap(19, 19, 19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSelectedItemLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSelectedProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSelectedItemLayout.setVerticalGroup(
            pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSelectedItemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlSelectedItemLayout.createSequentialGroup()
                        .addComponent(lblSelectedProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSelectedItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCountSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncSelected)
                            .addComponent(btnDecSelected))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddBasket))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabs.addTab("Selected Item", pnlSelectedItem);

        jLabel1.setText("Product                     Amount                                 Cost");

        jLabel2.setText("Total:");

        lblTotal.setText("£0.00");

        javax.swing.GroupLayout pnlBasetItemsLayout = new javax.swing.GroupLayout(pnlBasetItems);
        pnlBasetItems.setLayout(pnlBasetItemsLayout);
        pnlBasetItemsLayout.setHorizontalGroup(
            pnlBasetItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        pnlBasetItemsLayout.setVerticalGroup(
            pnlBasetItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(pnlBasetItems);

        javax.swing.GroupLayout pnlBasketLayout = new javax.swing.GroupLayout(pnlBasket);
        pnlBasket.setLayout(pnlBasketLayout);
        pnlBasketLayout.setHorizontalGroup(
            pnlBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBasketLayout.createSequentialGroup()
                .addGroup(pnlBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBasketLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBasketLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)))
                    .addGroup(pnlBasketLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(76, 76, 76)
                        .addComponent(lblTotal)))
                .addGap(35, 35, 35))
        );
        pnlBasketLayout.setVerticalGroup(
            pnlBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBasketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal))
                .addContainerGap())
        );

        tabs.addTab("Basket", pnlBasket);

        mnuAdmin.setText("Login");
        jMenuBar1.add(mnuAdmin);

        mnuExit.setText("Exit");
        mnuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuExitMouseClicked
        // TODO add your handling code here:7
        System.exit(0);
    }//GEN-LAST:event_mnuExitMouseClicked

    private void btnIncSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncSelectedActionPerformed
        // TODO add your handling code here:
        try
        {
            int count = Integer.parseInt(txtCountSelected.getText());
            count++;
            txtCountSelected.setText(String.valueOf(count));
        }catch(NumberFormatException e)
        {
            txtCountSelected.setText("1");
            System.out.print("[!] Caught misplacedInput");
        }
    }//GEN-LAST:event_btnIncSelectedActionPerformed

    private void txtCountSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountSelectedActionPerformed
        // TODO add your handling code here:
        String text = txtCountSelected.getText();
        for(char c : text.toCharArray())
        {
            if(!isNumber(c))
            {
                txtCountSelected.setText("1");
                break;
            }
        }
    }//GEN-LAST:event_txtCountSelectedActionPerformed

    private void btnDecSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecSelectedActionPerformed
        // TODO add your handling code here:
        try
        {
            int count = Integer.parseInt(txtCountSelected.getText());
            count--;
            if(count < 0){count = 0;}
            txtCountSelected.setText(String.valueOf(count));
        }catch(NumberFormatException e)
        {
            txtCountSelected.setText("1");
            System.out.println("[!] Caught misplacedInput");
        }
    }//GEN-LAST:event_btnDecSelectedActionPerformed

    private boolean isNumber(char c)
    {
        return c == '0' || c == '1' || c == '2' || c == '3' || c == '4' 
                || c == '5' || c == '6' || c == '7' || c == '8' || c == '9';
    }
    
    public ArrayList<JButton> getProductButtons(ArrayList<Whisky> whiskys)
    {
        ArrayList<JButton> btns = new ArrayList();
        int x = 10;
        int y = 10;
        
        for(Whisky whisky : whiskys)
        {
            JButton btn = getProductButton(whisky.getName());
            btn.setActionCommand(String.valueOf(whisky.getId()));
            btn.setBounds(x, y, 110, 110);
            btn.addActionListener(new ActionListener()
            {
                @Override
                public void actionPerformed(ActionEvent e)
                {
                    setSelectedItem(e.getActionCommand());
                }
            });
            
            btns.add(btn);
            x+= 120;
            if(x >360)
            {
                x = 10;
                y += 120;
            }
        }
        
        return btns;
    }
    
    public void setSelectedItem(String id)
    {
        tabs.setEnabledAt(1, true);
        Whisky whisky = Whisky_Data.getSelectedWhisky(id);
        if(whisky == null){return;}
        lblSelectedProductName.setText(whisky.getName());
        txtDescription.setText(whisky.getDescription());
        txtCountSelected.setText("1");
        
        tabs.setSelectedIndex(1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(epos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(epos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(epos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(epos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new epos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBasket;
    private javax.swing.JButton btnDecSelected;
    private javax.swing.JButton btnIncSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblSelectedProductName;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenu mnuAdmin;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JPanel pnlBasetItems;
    private javax.swing.JPanel pnlBasket;
    private javax.swing.JPanel pnlProducts;
    private javax.swing.JPanel pnlSelectedItem;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txtCountSelected;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
